#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

DESC="ShellHub Agent"
NAME=shellhub-agent
DAEMON=/usr/bin/shellhub
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Include defaults if available
[ -f /etc/default/$NAME ] && . /etc/default/$NAME

# Export all variable from /etc/default/shellhub-agent that are used by
# shellhub-agent.start
export SERVER_ADDRESS
export PRIVATE_KEY
export TENANT_ID

do_start()
{
        start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile \
                          --startas /bin/sh -- -c "exec shellhub-agent $DAEMON_ARGS >> "$LOGFILE" 2>&1"
}

do_stop()
{
        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
        RETVAL="$?"
        [ "$RETVAL" = 2 ] && return 2

        start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
        [ "$?" = 2 ] && return 2

        rm -f $PIDFILE
        return "$RETVAL"
}

case "$1" in
  start)
        printf "Starting $NAME: "
        do_start
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping $NAME: "
        do_stop
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|force-reload)
        do_stop
        sleep 1
        do_start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac
