#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

DESC="ShellHub Agent"
NAME=shellhub-agent
DAEMON=/usr/bin/shellhub
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Export all variable from /etc/default/shellhub-agent if available
[ -f /etc/default/$NAME ] && set -a && . /etc/default/$NAME && set +a

do_start()
{
        start-stop-daemon --start --background --quiet --pidfile $PIDFILE --make-pidfile \
                          --startas /bin/sh -- -c "exec $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1"
}

do_stop()
{
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        RETVAL="$?"
        rm -f $PIDFILE
        return "$RETVAL"
}

case "$1" in
  start)
        printf "Starting $NAME: "
        do_start
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping $NAME: "
        do_stop
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|force-reload)
        do_stop
        sleep 1
        do_start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac
